### ISSUE TITLE
Initialize fails when device in sleep mode

### ISSUE THREAD

**Issue by Martin-Furter** [ikalchev/py-sds011#1]
I created the following test program:

#!/usr/bin/python3
import sds011
import time
sensor = sds011.SDS011( "/dev/ttyUSB2", use_query_mode=True )
sensor.sleep( sleep=False )
time.sleep( 15 )
pm25, pm10 = sensor.query()
sensor.sleep()
print( "PM2.5: %6.1f" % pm25 )
print( "PM10:  %6.1f" % pm10 )

The first time after connecting the sensor it works, but after that when the sensor is in the sleep mode i get the following exception:

Traceback (most recent call last):
  File "./readout.py", line 10, in <module>
    sensor = sds011.SDS011( "/dev/ttyUSB2", use_query_mode=True )
  File "/home/mf/python/sensors/sds011/sds011/__init__.py", line 44, in __init__
    self.set_report_mode(active=not use_query_mode)
  File "/home/mf/python/sensors/sds011/sds011/__init__.py", line 76, in set_report_mode
    self._get_reply()
  File "/home/mf/python/sensors/sds011/sds011/__init__.py", line 55, in _get_reply
    if (sum(d for d in data) & 255) != raw[8]:
IndexError: index out of range

To get it working I added a check for reply length in function _get_reply() near line  171:
       if len(data) == 0:
            return None

I assume there is a timeout and that's the reason that 0 bytes are received. I did not check if more changes are needed to make it work properly, it seems to work fine with this change alone.

**Comment by peterbenedicic** [comment]
Hi, I am having exactly the same problem. Can you elaborate what and where exactly should be changed or even better, paste the changed code.
Tnx,
Peter

**Comment by Martin-Furter** [comment]
Here is  the whole file:
[`__init__.py`](https://github.com/ikalchev/py-sds011/files/3038397/__init__.py.txt)

- Martin

**Comment by Martin-Furter** [comment]
I looked into the code: When creating an SDS011() object the function set_report_mode() is called. The sensor seems to not answer to this message when in sleep mode. That's why the exception was thrown.

With my change the set_report_mode() error is ignored. That means the report mode will not be initialized. but since the device is in sleep mode it has been initialized before. So this is no problem.

**Comment by peterbenedicic** [comment]
Hi, I've just used your file and it's working flawlessly. Much appreciated! And thanks for explanation. Best regards,
Peter

**Comment by ikalchev** [comment]
Hi and thanks for the fix, I will add it to the code. Feel free to open a pull request if you want to do it.
